title: Daydreams of a physicist
description: Sometimes I catch myself thinking about physics.
author: Rafael Poliseli Teles
avatar: /assets/icon/logo.jpeg
subscribe: False

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
# twiter:
#   username: ngzhio
#   card: summary
# logo: logo.png
# social:
#   name: Rafael Poliseli Teles
#   links:
#     - https://twitter.com/ngzhio
#     - https://www.facebook.com/ngzhio
#     - https://github.com/ngzhio
lang: en
skin: midnight

future: True